### ISSUE TITLE
Feature request:  Whitelist?

### ISSUE THREAD

**Issue by Freddd13** [windingblack/obsidian-global-proxy#2]
Thanks for your work.
I have some video links inserted in my md files,  and some of them can be accessed without proxy. 
I'm not familiar with proxy principles, but I wonder if it is possible to  implement a whitelist scheme. Maybe a domain whitelist like proxifier or something like using browser proxy?

**Comment by windingblack** [comment]
I am sorry for the late reply. Please update to new version, it has a new blacklist featrue that would bypass local network traffic by default.

**Comment by Freddd13** [comment]
Thank you for the update.
